### ISSUE TITLE
Use descriptions for variables and outputs.

### ISSUE THREAD

**Issue by kravetsd** [rkasymaliev/terraform_test_project#1]
Please take a look on variables and outputs definitions in your code and apply best practices. 

Your outputs examples:
https://github.com/rkasymaliev/terraform_test_project/blob/dc5935849c67c27b20a5e7a938fb6c66d3e2be29/outputs.tf#L3

Your variables examples: 
https://github.com/rkasymaliev/terraform_test_project/blob/dc5935849c67c27b20a5e7a938fb6c66d3e2be29/variables.tf#L2-L9

Variables usually have some description, type, default values. Don't forget to use terraform fmt command.
https://www.terraform.io/language/values/variables

**Comment by rkasymaliev** [comment]
https://github.com/rkasymaliev/terraform_test_project/commit/0e86e2932533b4dd60d41102505edef41453ff87

**Comment by kravetsd** [comment]
Done
