### ISSUE TITLE
[Major] Hardcoded user in connection section for provisioners.

### ISSUE THREAD

**Issue by kravetsd** [rkasymaliev/terraform_test_project#2]
https://github.com/rkasymaliev/terraform_test_project/blob/dc5935849c67c27b20a5e7a938fb6c66d3e2be29/ec2-instance/main.tf#L49

**Comment by kravetsd** [comment]
- 1 ) Basic is  to make var.ami_id + var.ssh_user


- 2) advanced option:
ami_to_user_map = {
  centos = {
       ami_di       = id_2134125125
       ucername  = "centos"
  }
  ubuntu = {
       ami_di       = id_2134125125
       ucername  = "ubuntu"
  }
}

please take a look to "lookup" function. terraform.

**Comment by kravetsd** [comment]
Please switch to var.ami_id + var.ssh_user as a first iteration.

**Comment by rkasymaliev** [comment]
https://github.com/rkasymaliev/terraform_test_project/commit/72c8dfd9848ff98e8a1c61b22cedb5820236224d

**Comment by kravetsd** [comment]
Done
