### ISSUE TITLE
Stop using interpolation in your code. 

### ISSUE THREAD

**Issue by kravetsd** [rkasymaliev/terraform_test_project#6]
Here is an example:
https://github.com/rkasymaliev/terraform_test_project/blob/dc5935849c67c27b20a5e7a938fb6c66d3e2be29/ec2-instance/main.tf#L4

Extra interpolation is not required. It is deprecated in terraform versions higher then 0.11.
https://www.terraform.io/language/configuration-0-11/interpolation

**Comment by rkasymaliev** [comment]
https://github.com/rkasymaliev/terraform_test_project/commit/72c8dfd9848ff98e8a1c61b22cedb5820236224d#r70786535

**Comment by kravetsd** [comment]
Done
